### ISSUE TITLE
Add GitHub repo link to package.json to be listed on npm

### ISSUE THREAD

**Issue by aberba** [satyajitnayk/natural-cron#13]
This repo was so hard to find because it wasn't either in your medium blog post nor the npm package listing page. Can you please add it to the package.json file to make the repo discoverable? Maybe also link to repo on your medium blog post about it.

**Comment by satyajitnayk** [comment]
Thanks @aberba. I have added github url to package json in [release 1.0.2](https://github.com/satyajitnayk/natural-cron/releases/tag/1.0.2).
